# Generated by Django 4.1.6 on 2023-02-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Dte',
            new_name='Date',
        ),
    ]
